### PR TITLE
WIP: Serialization of simple values

### PR DESCRIPTION
**Pull request by Byron**
Related to #3

### CODE REVIEW

**Comment by oli-obk** [comment]
Wouldn't it be simpler to use `&'static[u8]` for the indentation and get rid of all the lifetimes?

**Comment by Byron** [comment]
It would certainly fix the issue, but considering the lifetimes have been specified already, and allow for more flexible use of strings in general (by not limiting them to be specified at compile time), I'd probably just keep them around.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/0m04EAlPibc).

*`serde-yaml #8 [refactor formatters]`*

[\thumb](https://youtu.be/0m04EAlPibc)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/EafUrYclM_w).

*`serde-yaml #10 [reading the SPEC and building the test-suite]`*

[\thumb](https://youtu.be/EafUrYclM_w)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/wjG3ggAyObA).

*`serde-yaml #11 [building the test-suite PT2 (gruntwork)]`*

[\thumb](https://youtu.be/wjG3ggAyObA)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/GJ11Of1Oi3s).

*`serde-yaml #9 [learn about YAML styles]`*

[\thumb](https://youtu.be/GJ11Of1Oi3s)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/EafUrYclM_w).

*`serde-yaml #10 [reading the SPEC and building the test-suite]`*

[\thumb](https://youtu.be/EafUrYclM_w)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/UK7MUGD78CY).

*`serde-yaml #11 [building the test-suite PT2 (gruntwork)]`*

[\thumb](https://youtu.be/UK7MUGD78CY)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/P3HbwfgnEsc).

*`serde-yaml #12 [building the test-suite PT3 (gruntwork)]`*

[\thumb](https://youtu.be/P3HbwfgnEsc)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/PIMj6kfmLoM).

*`serde-yaml #13 [building the test-suite PT4 (gruntwork)]`*

[\thumb](https://youtu.be/PIMj6kfmLoM)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/NRYIRm1VOtk).

*`serde-yaml #14 [additional presentation options]`*

[\thumb](https://youtu.be/NRYIRm1VOtk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/iVzLHF4HodM).

*`serde-yaml #15 [slowly getting into schemas and tags]`*

[\thumb](https://youtu.be/iVzLHF4HodM)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/apGjiVFjiKk).

*`serde-yaml #16 [finalize test-suite with examples]`*

[\thumb](https://youtu.be/apGjiVFjiKk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/JTQJ0tw4a2M).

*`serde-yaml #17 [reactoring PresentationDetails]`*

[\thumb](https://youtu.be/JTQJ0tw4a2M)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/4VQAErz2inE).

*`serde-yaml #18 [reviewing the public API and docs]`*

[\thumb](https://youtu.be/4VQAErz2inE)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/ihse3XQ3qho).

*`serde-yaml #19 [canonical presentation]`*

[\thumb](https://youtu.be/ihse3XQ3qho)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/zwCfpyNbjVs).

*`serde-yaml #20 [infrastructure for handling documents, encoding and byte order marks]`*

[\thumb](https://youtu.be/zwCfpyNbjVs)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/f9EPz3o-gj8).

*`serde-yaml #21 [serializing null (plain, flow)]`*

[\thumb](https://youtu.be/f9EPz3o-gj8)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/4GCgbsiHXxY).

*`serde-yaml #22 [Borrow for PresentationDetails]`*

[\thumb](https://youtu.be/4GCgbsiHXxY)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/R8tt2_CKjk0).

*`serde-yaml #23 [end of document markers (still failing)]`*

[\thumb](https://youtu.be/R8tt2_CKjk0)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/OTeJMfOgPkQ).

*`serde-yaml #24 [end of document markers works - nasty newlines]`*

[\thumb](https://youtu.be/OTeJMfOgPkQ)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/Nv6f9CIcNKs).

*`serde-yaml #25 [refactoring presentation options and encode_scalar]`*

[\thumb](https://youtu.be/Nv6f9CIcNKs)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/p-6658Londo).

*`serde-yaml #26 [remove Formatter and make encode_scalar a method]`*

[\thumb](https://youtu.be/p-6658Londo)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/XHte4kbuUGk).

*`serde-yaml #27 [non-string scalar handling and tests with null]`*

[\thumb](https://youtu.be/XHte4kbuUGk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/lpUi48QcrhY).

*`serde-yaml #28 [sequence serialization - basic infrastructure]`*

[\thumb](https://youtu.be/lpUi48QcrhY)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/l4M2Mrs2gGg).

*`serde-yaml #29 [fist simple block sequence serialization]`*

[\thumb](https://youtu.be/l4M2Mrs2gGg)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/D1WoiU_KL8c).

*`serde-yaml #30 [refactor elt_seq and additional sequence tests]`*

[\thumb](https://youtu.be/D1WoiU_KL8c)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/WseXcZZkDAM).

*`serde-yaml #31 [block mapping tests]`*

[\thumb](https://youtu.be/WseXcZZkDAM)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/aoufYEAP2kg).

*`serde-yaml #32 [mapping infrastructure PT.1]`*

[\thumb](https://youtu.be/aoufYEAP2kg)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/QgqwmsHxDzg).

*`serde-yaml #33 [mapping infrastructure PT.2 - all tags]`*

[\thumb](https://youtu.be/QgqwmsHxDzg)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/1q8Yb3fESrQ).

*`serde-yaml #35 [looking into yaml-rust]`*

[\thumb](https://youtu.be/1q8Yb3fESrQ)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/i75hP2XCVYw).

*`serde-yaml #36 [research on how to escape strings in JSON and YAML]`*

[\thumb](https://youtu.be/i75hP2XCVYw)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/WuqYJD0fbe8).

*`serde-yaml #37 [escaping infrastructure and initial JSON style escaping]`*

[\thumb](https://youtu.be/WuqYJD0fbe8)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/5kLdX8wTky8).

*`serde-yaml #38 [JSON and YAML escaping PT.1]`*

[\thumb](https://youtu.be/5kLdX8wTky8)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/wKEQ5nFQGYo).

*`serde-yaml #39 [refactoring and string analysis PT.2]`*

[\thumb](https://youtu.be/wKEQ5nFQGYo)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/TcMcOopjUVk).

*`serde-yaml #40 [string analysis PT.3]`*

[\thumb](https://youtu.be/TcMcOopjUVk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/mrPyrvt53ho).

*`serde-yaml #41 [string analysis works generally]`*

[\thumb](https://youtu.be/mrPyrvt53ho)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/TWQMk7ysWkk).

*`serde-yaml #42 [control character escapes and escaping finished]`*

[\thumb](https://youtu.be/TWQMk7ysWkk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/azOLU3mQkRc).

*`serde-yaml #43 [flow-style inheritance and minor refactoring]`*

[\thumb](https://youtu.be/azOLU3mQkRc)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/mg-pecw-Big).

*`serde-yaml #44 [flow-sequence null handling]`*

[\thumb](https://youtu.be/mg-pecw-Big)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/Mk--cqaVK08).

*`serde-yaml #45 [improved scalar encoding logic for better presentation]`*

[\thumb](https://youtu.be/Mk--cqaVK08)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/azP-bCRkxJk).

*`serde-yaml #46 [improvements to tags and whitespace handling]`*

[\thumb](https://youtu.be/azP-bCRkxJk)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/pTMwXj3WmrI).

*`serde-yaml #47 [simplified explicit entry handling]`*

[\thumb](https://youtu.be/pTMwXj3WmrI)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/Jdkvj0u9e8E).

*`serde-yaml #48 [multi-document handling and refactoring]`*

[\thumb](https://youtu.be/Jdkvj0u9e8E)

**Pull request merged**
